### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by kenmazaika** [daveline79/shoutr#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by DavidLineman** [comment]
Hey Ken, thanks for your feedback. I added the mobile meta tag: "<meta name="viewport" content="width=device-width, initial-scale=1">"

It seems to be working fine on mobile. Let me know your thoughts.

**Comment by kenmazaika** [comment]
Your code looks perfect here, @DavidLineman.  Thumbs up!
